# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set data = load_file_data("pyproject.toml") %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: ast_canopy
  version: {{ version }}

source:
  path: ../../../ast_canopy

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.28
    - ninja
  host:
    - python
    - pybind11
    - pip
    - scikit-build-core
    - clangdev >=18
    - llvmdev >=14
    - llvm >=14
  run:
    - cuda-version >=12.3
    - cuda-nvcc >=12.3
    - cuda-nvcc_{{ target_platform }} >=12.3
    - gcc >=10,<13
    - python
    - clangdev >=18

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: ast_canopy is a CUDA C++ device function header parser
