# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set data = load_file_data("pyproject.toml") %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}
{% set py_version = environ['CONDA_PY'] %}

package:
  name: ast_canopy
  version: {{ PROJECT_VERSION }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=numbast-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=numbast-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

source:
  path: ../../..

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.29
    - ninja
  host:
    - python
    - pybind11
    - pip
    - scikit-build-core
    - clangdev >=18,<22.0
    - llvmdev >=14
    - llvm >=14
  run:
    - cuda-version >=12.5
    - cuda-nvcc >=12.5
    - python
    - clangdev >=18,<22.0
    # libcurand-dev contains `curand_mtgp32_kernel.h`, which is needed by clang
    # CUDA mode to function properly. See:
    # https://clang.llvm.org/doxygen/____clang__cuda__runtime__wrapper_8h_source.html
    - libcurand-dev

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: ast_canopy is a CUDA C++ device function header parser
