# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set data = load_file_data("pyproject.toml") %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: ast_canopy
  version: {{ version }}

source:
  path: ../../../ast_canopy

build:
  script: {{ PYTHON }} -m pip install . -vv && mv {{ SP_DIR }}/libastcanopy.so {{ PREFIX }}/lib
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.28
    - pybind11
    - cffi
    - pynvjitlink >=0.2
    - clangdev >=18
    - ninja
    - sysroot_{{ target_platform }} 2.17
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cuda-version {{ cuda_compiler_version }}
    - python
    - pip
    - scikit-build-core
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - numba >=0.58
    - pynvjitlink >=0.2
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x.x') }}
    - cuda-toolkit {{ cuda_compiler_version }}
    - cuda-python {{ cuda_compiler_version }}
    - clangdev >=18

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: ast_canopy ast parsing...
