// SPDX-License-Identifier: Apache-2.0
// Automatically generated by Numbast; do not edit.
// Source config: examples/cuda_oxide_c_device/numbast.yaml
// Raw declarations are unsafe and resolve directly from external CUDA LTOIR.

#[allow(unused_imports)]
use cuda_device::device;

/// Opaque POD storage used behind a device-extern pointer.
/// C layout: size 16, alignment 4.
#[allow(non_camel_case_types)]
pub type round1_options = [u32; 4];
const _: [(); 16] = [(); core::mem::size_of::<round1_options>()];
const _: [(); 4] = [(); core::mem::align_of::<round1_options>()];

#[allow(non_camel_case_types)]
pub type round1_mode = u32;

#[allow(non_camel_case_types)]
pub type round1_handle_t = u64;

#[allow(non_upper_case_globals)]
pub const ROUND1_MODE_ADD: round1_mode = 0;
pub const ROUND1_MODE_SUBTRACT: round1_mode = 1;
pub const ROUND1_DEFAULT_HANDLE: round1_handle_t = 0;

#[device]
#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn round1_accumulate(values: *const i32, count: u64) -> i32;
    pub fn round1_add(left: i32, right: i32) -> i32;
    pub fn round1_apply(value: i32, mode: round1_mode, options: *const round1_options) -> i32;
}

// Prefix-stripped public names preserve the native link symbol above.
pub use self::round1_accumulate as accumulate;
pub use self::round1_add as add;
pub use self::round1_apply as apply;
