# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
reviews:
  profile: assertive # assertive / chill profile
  auto_review:
    enabled: true # Disable auto-review for this repository
