name: Compute matrix

outputs:
  BUILD_MATRIX:
    value: ${{ steps.compute-matrix.outputs.BUILD_MATRIX }}

runs:
  using: composite
  steps:
    - name: Compute matrix
      id: compute-matrix
      shell: bash
      run: |
        set -eo pipefail

        export BUILD_MATRIX="
        - { CUDA_VER: '12.2.2', ARCH: 'amd64', PY_VER: '3.9', LINUX_VER: 'centos7' }
        - { CUDA_VER: '12.2.2', ARCH: 'arm64', PY_VER: '3.9', LINUX_VER: 'rockylinux8' }
        "

        echo "BUILD_MATRIX=$(
          yq -n -o json 'env(BUILD_MATRIX)' | \
          jq -c '.' \
        )" | tee --append "${GITHUB_OUTPUT}"
