# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Render a CUDA-Oxide binding plan as a Rust source module."""

from __future__ import annotations

from numbast.cuda_oxide_binding_model import (
    CudaOxideBindingPlan,
    CudaOxideFunction,
)
from numbast.errors import CudaOxideBindingError
from numbast.rust_types import rust_identifier

_RUST_MAX_WIDTH = 100


def _render_constants(plan: CudaOxideBindingPlan) -> list[str]:
    lines: list[str] = []
    occupied: dict[str, tuple[str, str, str]] = {}

    for enum in plan.enums:
        enum_type = (
            rust_identifier(enum.name)
            if enum.name
            else enum.rust_underlying_type
        )
        for name, value in enum.enumerators:
            try:
                rust_name = rust_identifier(name)
            except ValueError as error:
                raise CudaOxideBindingError(
                    [f"enum constant has invalid name {name!r}"]
                ) from error

            item = (name, enum_type, value)
            previous = occupied.get(rust_name)
            if previous is not None:
                if previous == item:
                    continue
                raise CudaOxideBindingError(
                    [
                        f"constant name collision: {previous[0]!r} and "
                        f"{name!r} both map to {rust_name!r}"
                    ]
                )
            occupied[rust_name] = item
            lines.append(f"pub const {rust_name}: {enum_type} = {value};")

    function_names = {
        rust_identifier(name): name
        for function in plan.functions
        for name in (function.native_name, function.public_name)
    }
    for rust_name, (name, _enum_type, _value) in occupied.items():
        function_name = function_names.get(rust_name)
        if function_name is not None:
            raise CudaOxideBindingError(
                [
                    f"constant {name!r} conflicts with function name "
                    f"{function_name!r}"
                ]
            )
    return lines


def _render_extern_function(
    function: CudaOxideFunction, plan: CudaOxideBindingPlan
) -> list[str]:
    parameters = [
        f"{parameter.rust_name}: {plan.render_rust_type(parameter.type_)}"
        for parameter in function.parameters
    ]
    result = ""
    if not (
        function.return_type.base_name == "void"
        and not function.return_type.layers
    ):
        result = f" -> {plan.render_rust_type(function.return_type)}"

    name = rust_identifier(function.native_name)
    single_line = f"    pub fn {name}({', '.join(parameters)}){result};"
    if len(single_line) <= _RUST_MAX_WIDTH:
        return [single_line]
    return [
        f"    pub fn {name}(",
        *(f"        {parameter}," for parameter in parameters),
        f"    ){result};",
    ]


def render_cuda_oxide_bindings(plan: CudaOxideBindingPlan) -> str:
    """Return an includable Rust module for a completed binding plan."""

    constant_lines = _render_constants(plan)
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Automatically generated by Numbast; do not edit.",
        "// Raw declarations are unsafe and resolve directly from external CUDA LTOIR.",
        "",
        "#[allow(unused_imports)]",
        "use cuda_device::device;",
        "",
    ]

    for name, (storage, size, alignment) in sorted(
        plan.cuda_aliases.items()
    ):
        rust_name = rust_identifier(name)
        lines.extend(
            [
                f"/// CUDA ABI storage: size {size}, alignment {alignment}.",
                "#[allow(non_camel_case_types)]",
                f"pub type {rust_name} = {storage};",
                f"const _: [(); {size}] = [(); core::mem::size_of::<{rust_name}>()];",
                (
                    f"const _: [(); {alignment}] = "
                    f"[(); core::mem::align_of::<{rust_name}>()];"
                ),
                "",
            ]
        )

    for struct in plan.structs:
        rust_name = rust_identifier(struct.name)
        lines.extend(
            [
                "/// Opaque POD storage used behind a device-extern pointer.",
                f"/// C layout: size {struct.size}, alignment {struct.alignment}.",
                "#[allow(non_camel_case_types)]",
                f"pub type {rust_name} = {struct.storage_type};",
                f"const _: [(); {struct.size}] = [(); core::mem::size_of::<{rust_name}>()];",
                (
                    f"const _: [(); {struct.alignment}] = "
                    f"[(); core::mem::align_of::<{rust_name}>()];"
                ),
                "",
            ]
        )

    for enum in plan.enums:
        if not enum.name:
            continue
        lines.extend(
            [
                "#[allow(non_camel_case_types)]",
                (
                    f"pub type {rust_identifier(enum.name)} = "
                    f"{enum.rust_underlying_type};"
                ),
                "",
            ]
        )

    for type_alias in plan.type_aliases:
        if type_alias.name in plan.cuda_aliases:
            continue
        lines.extend(
            [
                "#[allow(non_camel_case_types)]",
                (
                    f"pub type {rust_identifier(type_alias.name)} = "
                    f"{plan.render_rust_type(type_alias.underlying)};"
                ),
                "",
            ]
        )

    if constant_lines:
        lines.append("#[allow(non_upper_case_globals)]")
        lines.extend(constant_lines)
        lines.append("")

    lines.extend(
        ["#[device]", "#[allow(improper_ctypes)]", 'unsafe extern "C" {']
    )
    for function in plan.functions:
        lines.extend(_render_extern_function(function, plan))
    lines.extend(["}", ""])

    aliases = [
        function
        for function in plan.functions
        if function.public_name != function.native_name
    ]
    if aliases:
        lines.append(
            "// Prefix-stripped public names preserve the native link symbol above."
        )
        for function in aliases:
            lines.append(
                f"pub use self::{rust_identifier(function.native_name)} as "
                f"{rust_identifier(function.public_name)};"
            )
        lines.append("")

    return "\n".join(lines)
