# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: numbast-extensions
  version: {{ version }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=numbast-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=numbast-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

source:
  path: ../../../numbast_extensions

build:
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - cuda-version >=12.5
    - cuda-cudart-dev
    - python
    - numba >=0.59
    - numba-cuda
    - numbast =={{ version }}

  test:
    imports:
      - numbast_extensions

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: Numbast-extensions contains novel dtypes and useful device side bindings for Numba.cuda
