# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: numbast-extensions
  version: {{ version }}

source:
  path: ../../../numbast_extensions

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - numbast
  host:
    - cuda-version {{ cuda_compiler_version }}
    - cuda-cudart {{ cuda_compiler_version }}
    - python
    - pip
    - scikit-build-core
  run:
    - python
    - numba >=0.59
    - numbast
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x.x') }}

  test:
    imports:
      - numbast_extensions

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: Numbast-extensions contains novel dtypes and useful device side bindings for Numba.cuda
