# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: numbast
  version: {{ version }}

source:
  path: ../../../numbast

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:
    - libnvjitlink-dev

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.28
    - ninja
  host:
    - python
    - pip
  run:
    - ast_canopy
    - cuda-nvrtc
    - cuda-version >=12.5
    - numba >=0.59
    - python
    - pynvjitlink >=0.2

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: Numbast is a CUDA C++ to Numba.cuda binding generator
