# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}
{% set py_version = environ['CONDA_PY'] %}

package:
  name: numbast
  version: {{ version }}

source:
  path: ../../../numbast

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=numbast-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=numbast-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS
  script:
    - {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:
    - libnvjitlink-dev

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.28
    - ninja
  host:
    - python
    - pip
    - setuptools
  run:
    - ast_canopy >={{ version }}
    - cuda-nvrtc
    - cuda-version >=12.5
    - numba >=0.59
    - python
    - numba-cuda
    - pynvjitlink >=0.2
    - pyyaml
    - click
    - ruff

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: Numbast is a CUDA C++ to Numba.cuda binding generator
