# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0


name: numbast
channels:
  - rapidsai
  - numba
  - conda-forge
dependencies:
  - cmake>=3.28
  - clangdev>=17
  - numba
  - pybind11
  - pytest
  - cffi
  - mypy
  - pre-commit
  - cxx-compiler
  - cuda-version=12.4
  - cuda-toolkit
  - cuda-python=12.4
  - pynvjitlink
  - scikit-build-core
