// SPDX-License-Identifier: Apache-2.0
// Automatically generated by Numbast; do not edit.
// Source config: <programmatic>
// Raw declarations are unsafe and resolve directly from external CUDA LTOIR.

#[allow(unused_imports)]
use cuda_device::device;

#[allow(non_camel_case_types)]
pub type team_t = i32;

#[allow(non_upper_case_globals)]
pub const TEAM_WORLD: team_t = 0;

#[device]
#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn library_copy(r#in: *const f32, output: *const *mut i32) -> i32;
}

// Prefix-stripped public names preserve the native link symbol above.
pub use self::library_copy as copy;
