# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: numba-extension-bf16
  version: {{ version }}

source:
  path: ../../../numba_extensions/bf16

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake >=3.28
    - pybind11
    - cffi
    - clangdev >=18
    - ninja
    - ast_canopy
    - numbast
    - sysroot_{{ target_platform }} 2.17
  host:
    - cuda-toolkit {{ cuda_compiler_version }}
    - cuda-python {{ cuda_compiler_version }}
    - cuda-version {{ cuda_compiler_version }}
    - python
    - pip
    - scikit-build-core
  run:
    - python
    - numba >=0.58
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x.x') }}
    - cuda-toolkit {{ cuda_compiler_version }}
    - cuda-python {{ cuda_compiler_version }}

  test:
    imports:
      - bf16

about:
  license_family: Apache
  license_file: ../../../LICENSE
  summary: numbast ast parsing...
