
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build CONDA PKG

on:
 push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  torch:
    runs-on: linux-arm64-gpu-a100-latest-1
    container: # GPU jobs must run in a container
        # Numbast depends on conda installed CTK, thus system CTK should not matter. Similarly for python version.
        image: rapidsai/ci-conda:cuda12.2.2-ubuntu22.04-py3.10
        env:
          NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
    env:
      RAPIDS_TESTS_DIR: ${{ github.workspace }}/test-results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment, Build and Test Torch
        run: "ci/build_conda.sh"
