
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build CONDA PKG

on:
 push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      BUILD_MATRIX: ${{ steps.compute-matrix.outputs.BUILD_MATRIX }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute Build Matrix
        id: compute-matrix
        uses: ./.github/actions/compute-matrix
  build-conda:
    needs:
      - compute-matrix
    uses: ./.github/workflows/conda-python-build.yaml@conda-pkg
    with:
      build_type: branch
      script: "ci/build_conda.sh"
      matrix_filter: ${{ needs.compute-matrix.outputs.BUILD_MATRIX }}
