name: Build and Test

on:
  workflow_call:
    inputs:
      ubuntu_version:
        description: 'Ubuntu version'
        required: true
        type: string
      cuda_version:
        description: 'CUDA version'
        required: true
        type: string
      python_version:
        description: 'Python version'
        required: true
        type: string
      GPU:
        description: 'GPU model'
        required: true
        type: string
      CPU:
        description: 'CPU model'
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: linux-${{ inputs.CPU }}-gpu-${{ inputs.GPU }}-latest-1
    container: # GPU jobs must run in a container
        # Numbast depends on conda installed CTK, thus system CTK should not matter. Similarly for python version.
        image: rapidsai/ci-conda:cuda12.2.2-ubuntu${{ inputs.ubuntu_version }}-py3.10
        env:
          NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
    env:
      RAPIDS_TESTS_DIR: ${{ github.workspace }}/test-results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment, Build and Test
        run: |
          ci/setup_build_test.sh ${{ inputs.cuda_version }} ${{ inputs.python_version }}

      # Add your build and test steps here
