# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Test Torch and bfloat16

on:
    workflow_call:


defaults:
  run:
    shell: bash

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  torch:
    runs-on: linux-arm64-gpu-a100-latest-1
    container: # GPU jobs must run in a container
        # Numbast depends on conda installed CTK, thus system CTK should not matter. Similarly for python version.
        image: nvcr.io/nvidia/pytorch:24.08-py3
        env:
          NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
    env:
      RAPIDS_TESTS_DIR: ${{ github.workspace }}/test-results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment, Build and Test Torch
        run: |
          ci/setup_torch_test.sh
